using System;
using System.Collections.Generic;
using System.Text;

namespace Template.Config.EditorTools
{
    /// <summary>
    /// 代码生成：把 CSV 表结构变成强类型访问代码（<c>Configs.Item.Get(1001)</c>），
    /// 杜绝"到处手写 id 字符串/魔法数组下标"。生成物放在独立目录与独立程序集里，
    /// 带 <c>&lt;auto-generated&gt;</c> 头 —— 手写代码永不进那个目录，改数据只改 CSV。
    /// </summary>
    public static class ConfigCodeGenerator
    {
        /// <summary>生成物目录（相对项目根；与 <c>Template.Configs</c> 程序集同目录）。</summary>
        public const string GeneratedFolder = "Assets/_Project/Scripts/Configs/Generated";

        /// <summary>
        /// 生成物的命名空间。
        /// ⚠ 不能叫 <c>Template.Configs</c>：那样会与**类名** <c>Configs</c> 撞车 ——
        /// 在其它 <c>Template.*</c> 命名空间里写 <c>Configs.Item</c> 时，编译器会先把 `Configs`
        /// 解析成"同父命名空间下的命名空间 Template.Configs"（命名空间优先于 using 导入的类型），
        /// 于是找不到成员 Item 而报 CS0234。放在 <c>Template.Config.Generated</c> 下就没有这个歧义。
        /// </summary>
        public const string Namespace = "Template.Config.Generated";

        /// <summary>
        /// 生成全部文件（相对路径 → 文件内容）。表按名字排序 → 输出稳定，
        /// 内容没变就不会写盘（避免每次导入都触发一次脚本重编译）。
        /// </summary>
        public static Dictionary<string, string> Generate(IReadOnlyList<CsvTable> tables)
        {
            var sorted = new List<CsvTable>(tables);
            sorted.Sort((a, b) => string.CompareOrdinal(a.Name, b.Name));

            var files = new Dictionary<string, string>(StringComparer.Ordinal);
            for (int i = 0; i < sorted.Count; i++)
            {
                CsvTable table = sorted[i];
                files[$"{GeneratedFolder}/{ConfigTypeMap.RowTypeOf(table.Name)}.cs"] = GenerateRowFile(table);
                files[$"{GeneratedFolder}/{ConfigTypeMap.TableTypeOf(table.Name)}.cs"] = GenerateTableFile(table);
            }
            files[$"{GeneratedFolder}/Configs.cs"] = GenerateAccessorsFile(sorted);
            return files;
        }

        private static string GenerateRowFile(CsvTable table)
        {
            string rowType = ConfigTypeMap.RowTypeOf(table.Name);
            var sb = new StringBuilder();
            AppendHeader(sb, table.SourcePath);
            sb.AppendLine("using Template.Config;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{table.Name} 表的一行（列顺序与 CSV 一致；只读，写入由导入工具完成）。</summary>");
            sb.AppendLine("    [System.Serializable]");
            sb.AppendLine($"    public sealed class {rowType} : IConfigRow");
            sb.AppendLine("    {");

            for (int c = 0; c < table.ColumnCount; c++)
                sb.AppendLine($"        [SerializeField] private {FieldTypeOf(table, c)} {table.Fields[c]};");

            sb.AppendLine();
            for (int c = 0; c < table.ColumnCount; c++)
            {
                if (ConfigTypeMap.IsRowReference(table.Types[c]))
                {
                    sb.AppendLine();
                    sb.AppendLine($"        /// <summary>外键：指向 {ConfigTypeMap.ReferencedTable(table.Types[c])} 表的行（CSV 里写目标行 id）。</summary>");
                }
                sb.AppendLine($"        public {FieldTypeOf(table, c)} {PropertyNameOf(table.Fields[c])} => {table.Fields[c]};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateTableFile(CsvTable table)
        {
            string rowType = ConfigTypeMap.RowTypeOf(table.Name);
            string tableType = ConfigTypeMap.TableTypeOf(table.Name);
            var sb = new StringBuilder();
            AppendHeader(sb, table.SourcePath);
            sb.AppendLine("using Template.Config;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{table.Name} 表：行类型 <see cref=\"{rowType}\"/>。</summary>");
            sb.AppendLine($"    public sealed class {tableType} : ConfigTableBase<{rowType}> {{ }}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateAccessorsFile(List<CsvTable> sorted)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     本文件由配置表管线自动生成（菜单：Tools/配置表/全部导入），请勿手改 —— 它由 Data/Configs/*.csv 决定。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using Template.Config;");
            sb.AppendLine("using Template.Core.Services;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 配置表统一访问入口：<c>Configs.Item.Get(1001)</c>。");
            sb.AppendLine("    ///");
            sb.AppendLine("    /// 表引用首次访问时从 <see cref=\"ConfigService\"/> 持有的配置库解析并缓存 ——");
            sb.AppendLine("    /// 所以访问发生在装配之后即可（装配前访问会拿到 null，装配后再访问会自动解析成功）。");
            sb.AppendLine("    /// 表是只读资产、运行期不会换，缓存是安全的。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class Configs");
            sb.AppendLine("    {");

            for (int i = 0; i < sorted.Count; i++)
                sb.AppendLine($"        private static {ConfigTypeMap.TableTypeOf(sorted[i].Name)} {FieldNameOf(sorted[i].Name)};");

            for (int i = 0; i < sorted.Count; i++)
            {
                CsvTable table = sorted[i];
                string tableType = ConfigTypeMap.TableTypeOf(table.Name);
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>{table.Name} 表。</summary>");
                sb.AppendLine($"        public static {tableType} {table.Name} => {FieldNameOf(table.Name)} != null ? {FieldNameOf(table.Name)} : ({FieldNameOf(table.Name)} = Resolve<{tableType}>());");
            }

            sb.AppendLine();
            sb.AppendLine("        private static TTable Resolve<TTable>() where TTable : UnityEngine.ScriptableObject");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!ServiceLocator.TryGet<ConfigService>(out ConfigService service))");
            sb.AppendLine("                return null; // 配置服务未注册（框架未自举 / 模块被删）——保持 null，下次访问再试");
            sb.AppendLine("            return service.GetTable<TTable>();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendHeader(StringBuilder sb, string csvPath)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     本文件由配置表管线自动生成（菜单：Tools/配置表/全部导入），请勿手改 —— 改数据请改 CSV：");
            sb.AppendLine($"//     {csvPath}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        private static string FieldTypeOf(CsvTable table, int column)
            => table.Types[column]; // 基础类型与行类型在代码里同名（int/float/bool/string/ItemConfig）

        /// <summary>列名 → 属性名（id → Id，drop_item → DropItem）。</summary>
        public static string PropertyNameOf(string column)
        {
            var sb = new StringBuilder(column.Length);
            bool upperNext = true;
            for (int i = 0; i < column.Length; i++)
            {
                char c = column[i];
                if (c == '_')
                {
                    upperNext = true;
                    continue;
                }
                sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                upperNext = false;
            }
            return sb.ToString();
        }

        /// <summary>表名 → 访问器背后的静态字段名（Item → _item）。</summary>
        private static string FieldNameOf(string tableName)
            => "_" + char.ToLowerInvariant(tableName[0]) + tableName.Substring(1);
    }
}
